# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff178ce4a7c89d0f9775da54238ddbc119eff68525afa931db9843f0fe9a422463e88928a41e0974b22cb538372ba3eceed3057c059c78bf3bdf3f483f58aa87

test:
  secret_key_base: 420efa729387cbddfb55ab4c6523d5ac6be91079cbf7eb66cf794d985b4bb97aca597cf00fa6934e5ab57f179d9e0463c1dd2d97b27fa5edccf37b97382ed50f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
